apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: default
  labels:
    app: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  strategy:
    type: Recreate   
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - name: unifi
        image: linuxserver/unifi-controller:5.11.50-ls40
        env:
        - name: "MEM_LIMIT"
          value: "1024M"
        - name: "PUID"
          value: "1000"
          name: "PGID"
          value: "1000"
        #readinessProbe:
          #tcpSocket:
            #port: ubnt-3478
          #initialDelaySeconds: 10
          #timeoutSeconds: 5
          #failureThreshold: 10
        #livenessProbe:
          #httpGet:
            #path: /
            #port: web
          #initialDelaySeconds: 10
          #timeoutSeconds: 5
          #failureThreshold: 10
        resources:
          requests:
            cpu: 100m
            memory: "1024Mi"
            ephemeral-storage: "200Mi"
        volumeMounts:
        - name: unifi
          mountPath: "/config"
          subPath: unifi/config
        ports:
        - containerPort: 6789
          name: ubnt-6789
          protocol: TCP
        - containerPort: 8080
          name: ubnt-8080
          protocol: TCP
        - containerPort: 8443
          name: ubnt-8443
          protocol: TCP
        - containerPort: 3478
          name: ubnt-3478
          protocol: UDP
        - containerPort: 8881
          name: ubnt-8881
          protocol: TCP
        - containerPort: 8882
          name: ubnt-8882
          protocol: TCP
        - containerPort: 10001
          name: ubnt-10001
          protocol: UDP
      volumes:
      - name: unifi
        persistentVolumeClaim:
          claimName: synology-unifi
