apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: default
  labels:
    app: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  strategy:
    type: Recreate   
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - name: unifi
      #  image: linuxserver/unifi-controller:latest
        image: jacobalberty/unifi:latest
        env:
        - name: "TZ"
          value: "America/Denver"
        - name: "JVM_INIT_HEAP_SIZE"
          value: "1024M"
        resources:
          requests:
            cpu: 100m
            memory: "750Mi"
        volumeMounts:
        - name: k8s-pv01
          mountPath: "unifi/data"
          subPath: unifi/data
        - name: k8s-pv01
          mountPath: "unifi/log"
          subPath: unifi/log
        - name: k8s-pv01
          mountPath: "unifi/cert"
          subPath: unifi/cert
        ports:
        - containerPort: 6789
          name: ubnt-6789
          protocol: TCP
        - containerPort: 8080
          name: ubnt-8080
          protocol: TCP
        - containerPort: 8443
          name: ubnt-8443
          protocol: TCP
        - containerPort: 3478
          name: ubnt-3478
          protocol: UDP
        - containerPort: 8881
          name: ubnt-8881
          protocol: TCP
        - containerPort: 8882
          name: ubnt-8882
          protocol: TCP
        - containerPort: 10001
          name: ubnt-10001
          protocol: UDP
      volumes:
      - name: k8s-pv01
        persistentVolumeClaim:
          claimName: synology-k8s-pv01
