apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi
  namespace: default
  labels:
    app: unifi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi
  strategy:
    type: Recreate   
  template:
    metadata:
      labels:
        app: unifi
    spec:
      containers:
      - name: unifi
        image: lscr.io/linuxserver/unifi-network-application:latest 
        env:
        - name: "MEM_LIMIT"
          value: "1024"
        - name: "PUID"
          value: "1000"
        - name: "PGID"
          value: "1000"
        - name: "TZ"
          value: "America/Denver"
        - name: "MONGO_USER"
          value: "unifi"
        - name: "MONGO_PASS"
          value: ""
        - name: "MONGO_HOST"
          value: "unifi-db"
        - name: "MONGO_PORT"
          value: "27017"
        - name: "MONGO_DBNAME"
          value: "unifi"
            #        - name: "MONGO_TLS"
            #          value: ""
            #        - name: "MONGO_AUTHSOURCE"
            #          value: ""
        resources:
          requests:
            cpu: 100m
            memory: "750Mi"
        volumeMounts:
        - name: k8s-pv01
          mountPath: "/config"
          subPath: unifi/config
        ports:
        - containerPort: 6789
          name: mbl-thrput-tst
          protocol: TCP
        - containerPort: 8080
          name: device-comtion
          protocol: TCP
        - containerPort: 8443
          name: admin-portal
          protocol: TCP
        - containerPort: 3478
          name: unifi-stun
          protocol: UDP
        - containerPort: 8880
          name: gst-http-redrct
          protocol: TCP
        - containerPort: 8882
          name: gst-https-rdrct
          protocol: TCP
        - containerPort: 10001
          name: ap-discovery
          protocol: UDP
      volumes:
      - name: k8s-pv01
        persistentVolumeClaim:
          claimName: synology-k8s-pv01
